# Please update dev-requirements accordingly when updating black and ruff versions.
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.282'
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black-jupyter

  - repo: https://github.com/crate-ci/typos
    rev: v1.16.8
    hooks:
      - id: typos
        args: []
